version: '3'
services:
  serviceregistry:
    image: 'manjildeuri/serviceregistry:0.0.1'
    container_name: 'serviceregistry'
    ports:
      - '8761:8761'
    healthcheck:
      test: [ "CMD","curl","-f","http://serviceregistry:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: 'manjildeuri/configserver:0.0.1'
    container_name: 'configserver'
    ports:
      - '9296:9296'
    healthcheck:
      test: [ "CMD","curl","-f","http://configserver:9296/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      serviceregistry:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
  cloudgateway:
    image: 'manjildeuri/cloudgateway:0.0.1'
    container_name: 'orderservice'
    ports:
      - '9090:9090'
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
  orderservice:
    image: 'manjildeuri/orderservice:0.0.1'
    container_name: 'orderservice'
    ports:
      - '8081:8081'
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
  productservice:
    image: 'manjildeuri/productservice:0.0.1'
    container_name: 'productservice'
    ports:
      - '8080:8080'
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
  paymentservice:
    image: 'manjildeuri/paymentservice:0.0.1'
    container_name: 'paymentservice'
    ports:
      - '8082:8082'
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka



